version: '3'

services:
  web:
    build: .
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
    depends_on:
      - database

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'

  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env/development/database
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
