version: '3'

services:
  web:
    build: .
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
    depends_on:
      - database

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
